# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CAV
                                 A QGIS plugin
 cota area volume
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-19
        copyright            : (C) 2022 by JC
        email                : oliveirajc@ufv.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CAV class from file CAV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .CAV import CAV
    return CAV(iface)